springboot 3.1.2 (#27)
* spring cloud stream source (deprecated) -> output-bindings
* wrap loadflow parameters of json notification messages in an object for spring cloud stream 4+ compatibility when the object is null
It works with 3.2.4 but with 4.0.3 i'm getting
java.lang.ClassCastException: class [B cannot be cast to class java.lang.String

For spring cloud stream 4 vs spring cloud stream 3, in both cases, our string is converted to a byte[] with content-type application/json, but for 3.2.4 the byte[] gets converted back to the original string, whereas with 4.0.3 it gets converted to the parsed json object.

-> "null"
-> [110, 117, 108, 108] (spring cloud to byte[])
-> null # instead of "null"

With 3.2.4 the byte[] gets converted to string here: https://github.com/spring-cloud/spring-cloud-stream/blob/6bc8330dcbdee52e44266cbf0f0043cf4fc3c0d4/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/converter/ApplicationJsonMessageMarshallingConverter.java#L109
With 4.0.3 it uses spring cloud function org.springframework.cloud.function.context.config.SmartCompositeMessageConverter which uses jackson readValue on the string.

With 4.0.3 if I send a non null object, I get the previous behavior (because of an intermediate try/catch in spring cloud stream which falls back to restoring the string, I guess not very good for performance and design?):
"com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type java.lang.String from Object value (token JsonToken.START_OBJECT)"
https://github.com/spring-cloud/spring-cloud-function/blob/cc740db82e27efee4e23af4ad8e1de6f6a6fc9e9/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/JsonMessageConverter.java#L98

NOTE: this is also the service that uses code which doesn't work with springboot 3.1.3 hibernate 6.2.7 HH-16811

Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>
Co-authored-by: HARPER Jon <jon.harper87@gmail.com>